version: '3.1'

services:
  db:
    container_name: db
    image: kapua/kapua-sql:${IMAGE_VERSION}
    ports:
      - "3306:3306"
  es:
    container_name: es
    image: opensearchproject/opensearch:1.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
      - "9600:9600"
    environment:
      - cluster.name=kapua-datastore
      - discovery.type=single-node
      - plugins.security.disabled=true
      - transport.host=_site_
      - transport.ping_schedule=-1
      - transport.tcp.connect_timeout=30s
  es-dashboard:
    container_name: es-dashboard
    image: opensearchproject/opensearch-dashboards:1.0.0
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=https://es:9200
      - plugins.security.disabled=true
  events-broker:
    container_name: events-broker
    image: kapua/kapua-events-broker:${IMAGE_VERSION}
    ports:
      - "5672:5672"
  broker:
    container_name: broker
    image: kapua/kapua-broker:${IMAGE_VERSION}
    expose:
      - 1893
    ports:
      - "1883:1883"
      - "8883:8883"
      - "61614:61614"
    depends_on:
      - db
      - es
      - events-broker
    environment:
      - CRYPTO_SECRET_KEY
      - KAPUA_DISABLE_SSL
      - KAPUA_DISABLE_DATASTORE
      - KAPUA_CRT
      - KAPUA_CA
      - KAPUA_KEY
      - KAPUA_KEY_PASSWORD
      - KAPUA_KEYSTORE
      - KAPUA_KEYSTORE_PASSWORD
      - LOGBACK_LOG_LEVEL
  kapua-console:
    container_name: kapua-console
    image: kapua/kapua-console:${IMAGE_VERSION}
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - broker
      - db
      - es
      - events-broker
    environment:
      - CRYPTO_SECRET_KEY
      - KAPUA_DISABLE_SSL
      - KAPUA_DISABLE_DATASTORE
      - KAPUA_CA
      - KAPUA_CRT
      - KAPUA_KEY
      - KAPUA_KEY_PASSWORD
      - KAPUA_KEYSTORE
      - KAPUA_KEYSTORE_PASSWORD
      - LOGBACK_LOG_LEVEL
      - KAPUA_CONSOLE_URL
      - KAPUA_OPENID_JWT_ISSUER
      - KAPUA_OPENID_CLIENT_ID
      - KAPUA_OPENID_CLIENT_SECRET
      - KAPUA_OPENID_JWT_AUDIENCE
      - KAPUA_OPENID_AUTH_ENDPOINT
      - KAPUA_OPENID_TOKEN_ENDPOINT
      - KAPUA_OPENID_LOGOUT_ENDPOINT
      - KEYCLOAK_URL
      - KEYCLOAK_CLIENT_ID
      - KEYCLOAK_REALM
  kapua-api:
    container_name: kapua-api
    image: kapua/kapua-api:${IMAGE_VERSION}
    ports:
      - "8081:8080"
      - "8444:8443"
    depends_on:
      - broker
      - db
      - es
      - events-broker
    environment:
      - API_CORS_ORIGINS_ALLOWED
      - CRYPTO_SECRET_KEY
      - KAPUA_DISABLE_SSL
      - KAPUA_DISABLE_DATASTORE
      - KAPUA_CA
      - KAPUA_CRT
      - KAPUA_KEY
      - KAPUA_KEY_PASSWORD
      - KAPUA_KEYSTORE
      - KAPUA_KEYSTORE_PASSWORD
      - LOGBACK_LOG_LEVEL
      - SWAGGER=${KAPUA_SWAGGER_ENABLE:-true}
  job-engine:
    container_name: job-engine
    image: kapua/kapua-job-engine:${IMAGE_VERSION}
    expose:
      - 8080
    depends_on:
      - broker
      - db
      - events-broker
    environment:
      - CRYPTO_SECRET_KEY
      - KAPUA_DISABLE_SSL
      - KAPUA_DISABLE_DATASTORE
      - KAPUA_CA
      - KAPUA_CRT
      - KAPUA_KEY
      - KAPUA_KEY_PASSWORD
      - KAPUA_KEYSTORE
      - KAPUA_KEYSTORE_PASSWORD
      - LOGBACK_LOG_LEVEL