{
 "title": "Monitoramento do Sistema de Arrefecimento Estudantil ( ICMC - USP )",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sensor_type",
    "label": "Tipo de Sensor",
    "query": "select sensor_type from sensor;"
   },
   { "name": "sensor_id", "label": "Sensor", "query": "select sensor_id from sensor" },
   {
    "name": "building_name",
    "label": "Prédio",
    "query": "select building_name from building"
   },
   { "name": "site_name", "label": "Campus", "query": "select site_name from site" },
   {
    "name": "room",
    "label": "Sala",
    "query": "select room_number from room where room_number='LAB1008'"
   },
   { "name": "room_type", "label": "Tipo de Sala", "query": "select room_type from room" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://icmc.usp.br/templates/icmc2015/img/logo.png\" alt=\"Logo ICMC\" style=\"display: block; margin: 0 auto;\">\n"
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Potência Utilizada",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metrics.power.dbl",
       "hide": false,
       "id": "1",
       "type": "avg"
      },
      { "field": "metrics.power.lng", "id": "3", "type": "avg" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Temperatura Atual",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "metrics.temperature.dbl", "id": "1", "type": "avg" },
      { "field": "metrics.temperature.lng", "id": "3", "type": "avg" }
     ],
     "query": "metrics.sensor_type.str:$sensor_type AND metrics.sensor_id.str:$sensor_id",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Umidade Atual",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "metrics.humidity.dbl", "id": "1", "type": "avg" },
      { "field": "metrics.humidity.lng", "id": "3", "type": "avg" }
     ],
     "query": "metrics.sensor_type.str:$sensor_type AND metrics.sensor_id.str:$sensor_id",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Humidade Relativa do Ar",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "metrics.humidity.lng", "id": "3", "type": "avg" },
      { "field": "metrics.humidity.dbl", "id": "4", "type": "avg" }
     ],
     "query": "metrics.sensor_type.str:$sensor_type AND metrics.sensor_id.str:$sensor_id",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Temperatura Cº",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "4", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "metrics.temperature.dbl", "id": "1", "type": "avg" },
      { "field": "metrics.temperature.lng", "id": "3", "type": "avg" }
     ],
     "query": "metrics.sensor_type.str:$sensor_type AND metrics.sensor_id.str:$sensor_id",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Detecção de Anomalias",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "data_end_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "anomaly_score", "id": "1", "type": "max" },
      { "field": "confidence", "id": "3", "type": "max" }
     ],
     "timeField": "data_end_time"
    }
   ]
  },
  {
   "title": "Detecção de Anomalias",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "anomaly_score", "id": "1", "type": "max" },
      { "field": "confidence", "id": "3", "type": "max" },
      { "id": "4", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Potência Energética",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "metrics.power.dbl", "id": "1", "type": "avg" },
      { "field": "metrics.power.lng", "id": "3", "type": "avg" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Corrente",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "metrics.current.dbl", "id": "1", "type": "avg" },
      { "field": "metrics.current.lng", "id": "3", "type": "avg" }
     ],
     "timeField": "timestamp"
    }
   ]
  }
 ]
}